baseURL = "https://adamyuan.xyz"
title = "AdamYuan->Blog"
theme = "hugo-notepadium"
copyright = "©2019 AdamYuan."

languageCode = "zh-cn"
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = "img/avatar.png"
license = ""  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.profile]
enable = true
github = "AdamYuan"  # https://github.com/XXX
email = "y13916619121@126.com"  # mailto:XXX@mail.com

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github"
darkTheme = "monokai"  # apply this theme in dark mode

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/
