baseURL = "https://adamyuan.xyz/"
languageCode = "en"
defaultContentLanguage = "en"
title = "AdamYuan->Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "beautifulhugo"
preserveTaxonomyNames = true
hasCJKLanguage = true
paginate = 5
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "&copy; 2018. All rights reserved."
dateFormat = "02 Jan 2006, 15:04"

[params]
  googleAnalytics = "UA-122304331-1"
  disqusShortname = "adamyuan-blog"

[author]
  name = "AdamYuan"
  email = "y13916619121@126.com"
  github = "AdamYuan"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  weight = 1 
  name = "Home"
  identifier = "home"
  url = "/"

[[menu.main]]
  weight = 2
  name = "Categories"
  identifier = "categories"
  url = "/categories/"

